overlay/var/www/railsapp/config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.home '', :controller => 'welcome', :conditions => {:method => :get}

  map.signin 'login', :controller => 'account', :action => 'login',
             :conditions => {:method => [:get, :post]}
  map.signout 'logout', :controller => 'account', :action => 'logout',
              :conditions => {:method => :get}
  map.connect 'account/register', :controller => 'account', :action => 'register',
              :conditions => {:method => [:get, :post]}
  map.connect 'account/lost_password', :controller => 'account', :action => 'lost_password',
              :conditions => {:method => [:get, :post]}
  map.connect 'account/activate', :controller => 'account', :action => 'activate',
              :conditions => {:method => :get}

  map.connect 'projects/:id/wiki', :controller => 'wikis',
              :action => 'edit', :conditions => {:method => :post}
  map.connect 'projects/:id/wiki/destroy', :controller => 'wikis',
              :action => 'destroy', :conditions => {:method => [:get, :post]}

  map.with_options :controller => 'messages' do |messages_routes|
    messages_routes.with_options :conditions => {:method => :get} do |messages_views|
      messages_views.connect 'boards/:board_id/topics/new', :action => 'new'
      messages_views.connect 'boards/:board_id/topics/:id', :action => 'show'
      messages_views.connect 'boards/:board_id/topics/:id/edit', :action => 'edit'
    end
    messages_routes.with_options :conditions => {:method => :post} do |messages_actions|
      messages_actions.connect 'boards/:board_id/topics/new', :action => 'new'
      messages_actions.connect 'boards/:board_id/topics/preview', :action => 'preview'
      messages_actions.connect 'boards/:board_id/topics/quote/:id', :action => 'quote'
      messages_actions.connect 'boards/:board_id/topics/:id/replies', :action => 'reply'
      messages_actions.connect 'boards/:board_id/topics/:id/edit', :action => 'edit'
      messages_actions.connect 'boards/:board_id/topics/:id/destroy', :action => 'destroy'
    end
  end

  map.auto_complete_issues '/issues/auto_complete', :controller => 'auto_completes',
                           :action => 'issues', :conditions => { :method => :get }
  map.preview_new_issue '/issues/preview/new/:project_id', :controller => 'previews',
                        :action => 'issue'
  map.preview_edit_issue '/issues/preview/edit/:id', :controller => 'previews',
                         :action => 'issue'
  map.issues_context_menu '/issues/context_menu',
                          :controller => 'context_menus', :action => 'issues'

  map.issue_changes '/issues/changes', :controller => 'journals', :action => 'index'
  map.quoted_issue '/issues/:id/quoted', :controller => 'journals', :action => 'new',
                   :id => /\d+/, :conditions => { :method => :post }

  map.connect '/journals/diff/:id', :controller => 'journals', :action => 'diff',
              :id => /\d+/, :conditions => { :method => :get }
  map.connect '/journals/edit/:id', :controller => 'journals', :action => 'edit',
              :id => /\d+/, :conditions => { :method => [:get, :post] }

  map.with_options :controller => 'gantts', :action => 'show' do |gantts_routes|
    gantts_routes.connect '/projects/:project_id/issues/gantt'
    gantts_routes.connect '/projects/:project_id/issues/gantt.:format'
    gantts_routes.connect '/issues/gantt.:format'
  end

  map.with_options :controller => 'calendars', :action => 'show' do |calendars_routes|
    calendars_routes.connect '/projects/:project_id/issues/calendar'
    calendars_routes.connect '/issues/calendar'
  end

  map.with_options :controller => 'reports', :conditions => {:method => :get} do |reports|
    reports.connect 'projects/:id/issues/report', :action => 'issue_report'
    reports.connect 'projects/:id/issues/report/:detail', :action => 'issue_report_details'
  end

  map.connect 'my/account', :controller => 'my', :action => 'account',
              :conditions => {:method => [:get, :post]}
  map.connect 'my/page', :controller => 'my', :action => 'page',
              :conditions => {:method => :get}
  map.connect 'my', :controller => 'my', :action => 'index',
              :conditions => {:method => :get}
  map.connect 'my/reset_rss_key', :controller => 'my', :action => 'reset_rss_key',
              :conditions => {:method => :post}
  map.connect 'my/reset_api_key', :controller => 'my', :action => 'reset_api_key',
              :conditions => {:method => :post}
  map.connect 'my/password', :controller => 'my', :action => 'password',
              :conditions => {:method => [:get, :post]}
  map.connect 'my/page_layout', :controller => 'my', :action => 'page_layout',
              :conditions => {:method => :get}
  map.connect 'my/add_block', :controller => 'my', :action => 'add_block',
              :conditions => {:method => :post}
  map.connect 'my/remove_block', :controller => 'my', :action => 'remove_block',
              :conditions => {:method => :post}
  map.connect 'my/order_blocks', :controller => 'my', :action => 'order_blocks',
              :conditions => {:method => :post}

  map.with_options :controller => 'users' do |users|
    users.user_membership 'users/:id/memberships/:membership_id',
                          :action => 'edit_membership',
                          :conditions => {:method => :put}
    users.connect 'users/:id/memberships/:membership_id',
                  :action => 'destroy_membership',
                  :conditions => {:method => :delete}
    users.user_memberships 'users/:id/memberships',
                           :action => 'edit_membership',
                           :conditions => {:method => :post}
  end
  map.resources :users

  map.connect 'projects/:project_id/roadmap', :controller => 'versions', :action => 'index'

  map.preview_news '/news/preview', :controller => 'previews', :action => 'news'
  map.connect 'news/:id/comments', :controller => 'comments',
              :action => 'create', :conditions => {:method => :post}
  map.connect 'news/:id/comments/:comment_id', :controller => 'comments',
              :action => 'destroy', :conditions => {:method => :delete}

  map.connect 'watchers/new', :controller=> 'watchers', :action => 'new',
              :conditions => {:method => :get}
  map.connect 'watchers', :controller=> 'watchers', :action => 'create',
              :conditions => {:method => :post}
  map.connect 'watchers/append', :controller=> 'watchers', :action => 'append',
              :conditions => {:method => :post}
  map.connect 'watchers/destroy', :controller=> 'watchers', :action => 'destroy',
              :conditions => {:method => :post}
  map.connect 'watchers/watch', :controller=> 'watchers', :action => 'watch',
              :conditions => {:method => :post}
  map.connect 'watchers/unwatch', :controller=> 'watchers', :action => 'unwatch',
              :conditions => {:method => :post}
  map.connect 'watchers/autocomplete_for_user', :controller=> 'watchers', :action => 'autocomplete_for_user',
              :conditions => {:method => :get}

  map.with_options :conditions => {:method => :get} do |project_views|
    project_views.connect 'projects/:id/settings/:tab',
                          :controller => 'projects', :action => 'settings'
    project_views.connect 'projects/:project_id/issues/:copy_from/copy',
                          :controller => 'issues', :action => 'new'
  end

  map.resources :projects, :member => {
    :copy => [:get, :post],
    :settings => :get,
    :modules => :post,
    :archive => :post,
    :unarchive => :post
  } do |project|
    project.resource :enumerations, :controller => 'project_enumerations',
                     :only => [:update, :destroy]
    project.issue_form 'issues/new', :controller => 'issues',
                       :action => 'new', :conditions => {:method => [:post, :put]}
    project.resources :issues, :only => [:index, :new, :create] do |issues|
      issues.resources :time_entries, :controller => 'timelog',
                       :collection => {:report => :get}
    end

    project.resources :files, :only => [:index, :new, :create]
    project.resources :versions, :shallow => true,
                      :collection => {:close_completed => :put},
                      :member => {:status_by => :post}
    project.resources :news, :shallow => true
    project.resources :time_entries, :controller => 'timelog',
                      :collection => {:report => :get}
    project.resources :queries, :only => [:new, :create]
    project.resources :issue_categories, :shallow => true
    project.resources :documents, :shallow => true, :member => {:add_attachment => :post}
    project.resources :boards
    project.resources :repositories, :shallow => true, :except => [:index, :show],
                      :member => {:committers => [:get, :post]}
    project.resources :memberships, :shallow => true, :controller => 'members',
                      :only => [:index, :show, :create, :update, :destroy],
                      :collection => {:autocomplete => :get}

    project.wiki_start_page 'wiki', :controller => 'wiki', :action => 'show', :conditions => {:method => :get}
    project.wiki_index 'wiki/index', :controller => 'wiki', :action => 'index', :conditions => {:method => :get}
    project.wiki_diff 'wiki/:id/diff/:version', :controller => 'wiki', :action => 'diff', :version => nil
    project.wiki_diff 'wiki/:id/diff/:version/vs/:version_from', :controller => 'wiki', :action => 'diff'
    project.wiki_annotate 'wiki/:id/annotate/:version', :controller => 'wiki', :action => 'annotate'
    project.resources :wiki, :except => [:new, :create], :member => {
      :rename => [:get, :post],
      :history => :get,
      :preview => :any,
      :protect => :post,
      :add_attachment => :post
    }, :collection => {
      :export => :get,
      :date_index => :get
    }
  end

overlay/var/www/railsapp/app/models/group.rb
# Redmine - project management software
# Copyright (C) 2006-2011  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class Group < Principal
  has_and_belongs_to_many :users, :after_add => :user_added,
                                  :after_remove => :user_removed

  acts_as_customizable

  validates_presence_of :lastname
  validates_uniqueness_of :lastname, :case_sensitive => false
  validates_length_of :lastname, :maximum => 30

  before_destroy :remove_references_before_destroy

  def to_s
    lastname.to_s
  end

  alias :name :to_s

  def user_added(user)
    members.each do |member|
      next if member.project.nil?
      user_member = Member.find_by_project_id_and_user_id(member.project_id, user.id) || Member.new(:project_id => member.project_id, :user_id => user.id)
      member.member_roles.each do |member_role|
        user_member.member_roles << MemberRole.new(:role => member_role.role, :inherited_from => member_role.id)
      end
      user_member.save!
    end
  end

  def user_removed(user)
    members.each do |member|
      MemberRole.find(:all, :include => :member,
                            :conditions => ["#{Member.table_name}.user_id = ? AND #{MemberRole.table_name}.inherited_from IN (?)", user.id, member.member_role_ids]).each(&:destroy)
    end
  end

  def self.human_attribute_name(attribute_key_name, *args)
    attr_name = attribute_key_name.to_s
    if attr_name == 'lastname'
      attr_name = "name"
    end
    super(attr_name, *args)
  end

  private

  # Removes references that are not handled by associations
  def remove_references_before_destroy
    return if self.id.nil?

    Issue.update_all 'assigned_to_id = NULL', ['assigned_to_id = ?', id]
  end
end

overlay/var/www/railsapp/app/helpers/projects_helper.rb
# encoding: utf-8
#
# Redmine - project management software
# Copyright (C) 2006-2011  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module ProjectsHelper
  def link_to_version(version, options = {})
    return '' unless version && version.is_a?(Version)
    link_to_if version.visible?, format_version_name(version), { :controller => 'versions', :action => 'show', :id => version }, options
  end

  def project_settings_tabs
    tabs = [{:name => 'info', :action => :edit_project, :partial => 'projects/edit', :label => :label_information_plural},
            {:name => 'modules', :action => :select_project_modules, :partial => 'projects/settings/modules', :label => :label_module_plural},
            {:name => 'members', :action => :manage_members, :partial => 'projects/settings/members', :label => :label_member_plural},
            {:name => 'versions', :action => :manage_versions, :partial => 'projects/settings/versions', :label => :label_version_plural},
            {:name => 'categories', :action => :manage_categories, :partial => 'projects/settings/issue_categories', :label => :label_issue_category_plural},
            {:name => 'wiki', :action => :manage_wiki, :partial => 'projects/settings/wiki', :label => :label_wiki},
            {:name => 'repositories', :action => :manage_repository, :partial => 'projects/settings/repositories', :label => :label_repository_plural},
            {:name => 'boards', :action => :manage_boards, :partial => 'projects/settings/boards', :label => :label_board_plural},
            {:name => 'activities', :action => :manage_project_activities, :partial => 'projects/settings/activities', :label => :enumeration_activities}
            ]
    tabs.select {|tab| User.current.allowed_to?(tab[:action], @project)}
  end

  def parent_project_select_tag(project)
    selected = project.parent
    # retrieve the requested parent project
    parent_id = (params[:project] && params[:project][:parent_id]) || params[:parent_id]
    if parent_id
      selected = (parent_id.blank? ? nil : Project.find(parent_id))
    end

    options = ''
    options << "<option value=''></option>" if project.allowed_parents.include?(nil)
    options << project_tree_options_for_select(project.allowed_parents.compact, :selected => selected)
    content_tag('select', options.html_safe, :name => 'project[parent_id]', :id => 'project_parent_id')
  end

  # Renders a tree of projects as a nested set of unordered lists
  # The given collection may be a subset of the whole project tree
  # (eg. some intermediate nodes are private and can not be seen)
  def render_project_hierarchy(projects)
    s = ''
    if projects.any?
      ancestors = []
      original_project = @project
      projects.each do |project|
        # set the project environment to please macros.
        @project = project
        if (ancestors.empty? || project.is_descendant_of?(ancestors.last))
          s << "<ul class='projects #{ ancestors.empty? ? 'root' : nil}'>\n"
        else
          ancestors.pop
          s << "</li>"
          while (ancestors.any? && !project.is_descendant_of?(ancestors.last))
            ancestors.pop
            s << "</ul></li>\n"
          end
        end
        classes = (ancestors.empty? ? 'root' : 'child')
        s << "<li class='#{classes}'><div class='#{classes}'>" +
               link_to_project(project, {}, :class => "project #{User.current.member_of?(project) ? 'my-project' : nil}")
        s << "<div class='wiki description'>#{textilizable(project.short_description, :project => project)}</div>" unless project.description.blank?
        s << "</div>\n"
        ancestors << project
      end
      s << ("</li></ul>\n" * ancestors.size)
      @project = original_project
    end
    s.html_safe
  end

  # Returns a set of options for a select field, grouped by project.
  def version_options_for_select(versions, selected=nil)
    grouped = Hash.new {|h,k| h[k] = []}
    versions.each do |version|
      grouped[version.project.name] << [version.name, version.id]
    end
    # Add in the selected
    if selected && !versions.include?(selected)
      grouped[selected.project.name] << [selected.name, selected.id]
    end

    if grouped.keys.size > 1
      grouped_options_for_select(grouped, selected && selected.id)
    else
      options_for_select((grouped.values.first || []), selected && selected.id)
    end
  end

  def format_version_sharing(sharing)
    sharing = 'none' unless Version::VERSION_SHARINGS.include?(sharing)
    l("label_version_sharing_#{sharing}")
  end
end

overlay/var/www/railsapp/app/views/projects/settings/_activities.html.erb
<% form_tag(project_enumerations_path(@project), :method => :put, :class => "tabular") do %>

<table class="list">
  <thead><tr>
    <th><%= l(:field_name) %></th>
    <th><%= l(:enumeration_system_activity) %></th>
    <% TimeEntryActivity.new.available_custom_fields.each do |value| %>
    <th><%= h value.name %></th>
    <% end %>
    <th style="width:15%;"><%= l(:field_active) %></th>
  </tr></thead>

  <% @project.activities(true).each do |enumeration| %>
  <% fields_for "enumerations[#{enumeration.id}]", enumeration do |ff| %>
  <tr class="<%= cycle('odd', 'even') %>">
    <td>
      <%= ff.hidden_field :parent_id, :value => enumeration.id unless enumeration.project %>
      <%= h(enumeration) %>
    </td>
    <td align="center" style="width:15%;"><%= checked_image !enumeration.project %></td>
    <% enumeration.custom_field_values.each do |value| %>
    <td align="center">
      <%= custom_field_tag "enumerations[#{enumeration.id}]", value %>
    </td>
    <% end %>
    <td align="center" style="width:15%;">
      <%= ff.check_box :active %>
    </td>
  </tr>
  <% end %>
  <% end %>
</table>

<div class="contextual">
<%= link_to(l(:button_reset), project_enumerations_path(@project),
            :method => :delete,
            :confirm => l(:text_are_you_sure),
            :class => 'icon icon-del') %>
</div>

<%= submit_tag l(:button_save) %>
<% end %>

overlay/var/www/railsapp/app/views/projects/settings/_boards.html.erb
<% if @project.boards.any? %>
<table class="list">
  <thead><tr>
    <th><%= l(:label_board) %></th>
    <th><%= l(:field_description) %></th>
    <th></th>
    <th></th>
  </tr></thead>
  <tbody>
<% @project.boards.each do |board|
  next if board.new_record? %>
  <tr class="<%= cycle 'odd', 'even' %>">
    <td><%=h board.name %></td>
    <td><%=h board.description %></td>
    <td align="center">
    <% if authorize_for("boards", "edit") %>
      <%= reorder_links('board', {:controller => 'boards', :action => 'update', :project_id => @project, :id => board}, :put) %>
    <% end %>
    </td>
    <td class="buttons">
    <% if User.current.allowed_to?(:manage_boards, @project) %>
      <%= link_to l(:button_edit), edit_project_board_path(@project, board), :class => 'icon icon-edit' %>
      <%= link_to l(:button_delete), project_board_path(@project, board), :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %>
		<% end %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% if User.current.allowed_to?(:manage_boards, @project) %>
<p><%= link_to l(:label_board_new), new_project_board_path(@project), :class => 'icon icon-add' %></p>
<% end %>

overlay/var/www/railsapp/app/views/projects/settings/_issue_categories.html.erb
<% if @project.issue_categories.any? %>
<table class="list">
  <thead><tr>
    <th><%= l(:label_issue_category) %></th>
    <th><%= l(:field_assigned_to) %></th>
    <th></th>
  </tr></thead>
  <tbody>
<% for category in @project.issue_categories %>
  <% unless category.new_record? %>
  <tr class="<%= cycle 'odd', 'even' %>">
    <td><%=h(category.name) %></td>
    <td><%=h(category.assigned_to.name) if category.assigned_to %></td>
    <td class="buttons">
    	<% if User.current.allowed_to?(:manage_categories, @project) %>
        <%= link_to l(:button_edit), edit_issue_category_path(category), :class => 'icon icon-edit' %>
        <%= link_to l(:button_delete), issue_category_path(category), :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %>
		  <% end %>
    </td>
  </tr>
  <% end %>
<% end %>
    </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<p><%= link_to l(:label_issue_category_new), new_project_issue_category_path(@project), :class => 'icon icon-add' if User.current.allowed_to?(:manage_categories, @project) %></p>

overlay/var/www/railsapp/app/views/projects/settings/_members.html.erb
<%= error_messages_for 'member' %>
<% roles = Role.find_all_givable
   members = @project.member_principals.find(:all, :include => [:roles, :principal]).sort %>

<div class="splitcontentleft">
<% if members.any? %>
<table class="list members">
  <thead><tr>
    <th><%= l(:label_user) %> / <%= l(:label_group) %></th>
    <th><%= l(:label_role_plural) %></th>
    <th style="width:15%"></th>
          <%= call_hook(:view_projects_settings_members_table_header, :project => @project) %>
  </tr></thead>
  <tbody>
  <% members.each do |member| %>
  <% next if member.new_record? %>
  <tr id="member-<%= member.id %>" class="<%= cycle 'odd', 'even' %> member">
  <td class="<%= member.principal.class.name.downcase %>"><%= link_to_user member.principal %></td>
  <td class="roles">
    <span id="member-<%= member.id %>-roles"><%=h member.roles.sort.collect(&:to_s).join(', ') %></span>
      <% remote_form_for(:membership, member, :url => membership_path(member),
                                          :method => :put,
                                          :html => { :id => "member-#{member.id}-roles-form", :class => 'hol' }) do |f| %>
        <p><% roles.each do |role| %>
        <label><%= check_box_tag 'membership[role_ids][]', role.id, member.roles.include?(role),
                                                       :disabled => member.member_roles.detect {|mr| mr.role_id == role.id && !mr.inherited_from.nil?} %> <%=h role %></label><br />
        <% end %></p>
        <%= hidden_field_tag 'membership[role_ids][]', '' %>
        <p><%= submit_tag l(:button_change), :class => "small" %>
        <%= link_to_function l(:button_cancel),
                             "$('member-#{member.id}-roles').show(); $('member-#{member.id}-roles-form').hide(); return false;"
             %></p>
      <% end %>
  </td>
  <td class="buttons">
      <%= link_to_function l(:button_edit),
                           "$('member-#{member.id}-roles').hide(); $('member-#{member.id}-roles-form').show(); return false;",
                           :class => 'icon icon-edit' %>
      <%= link_to_remote(
            l(:button_delete),
            { :url => membership_path(member),
              :method => :delete,
              :confirm => (!User.current.admin? && member.include?(User.current) ? l(:text_own_membership_delete_confirmation) : nil) },
            :title => l(:button_delete),
            :class => 'icon icon-del'
          ) if member.deletable? %>
  </td>
  <%= call_hook(:view_projects_settings_members_table_row, { :project => @project, :member => member}) %>
  </tr>
<% end; reset_cycle %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<% principals = Principal.active.not_member_of(@project).all(:limit => 100, :order => 'type, login, lastname ASC') %>

<div class="splitcontentright">
<% if roles.any? && principals.any? %>
  <% remote_form_for(:membership, @member, :url => project_memberships_path(@project), :method => :post,
                     :loading => '$(\'member-add-submit\').disable();',
                     :complete => 'if($(\'member-add-submit\')) $(\'member-add-submit\').enable();') do |f| %>
    <fieldset><legend><%=l(:label_member_new)%></legend>

    <p><%= label_tag "principal_search", l(:label_principal_search) %><%= text_field_tag 'principal_search', nil %></p>
    <%= observe_field(:principal_search,
                 :frequency => 0.5,
                 :update => :principals,
                 :url => autocomplete_project_memberships_path(@project),
                 :method => :get,
                 :before => '$("principal_search").addClassName("ajax-loading")',
                 :complete => '$("principal_search").removeClassName("ajax-loading")',
                 :with => 'q')
                  %>

    <div id="principals">
      <%= principals_check_box_tags 'membership[user_ids][]', principals %>
    </div>

    <p><%= l(:label_role_plural) %>:
    <% roles.each do |role| %>
      <label><%= check_box_tag 'membership[role_ids][]', role.id %> <%=h role %></label>
     <% end %></p>

    <p><%= submit_tag l(:button_add), :id => 'member-add-submit' %></p>
    </fieldset>
  <% end %>
<% end %>
</div>

overlay/var/www/railsapp/app/views/projects/settings/_modules.html.erb
<% form_for :project, @project,
            :url => { :action => 'modules', :id => @project },
            :html => {:id => 'modules-form',
                      :method => :post} do |f| %>

<div class="box">
<fieldset>
<legend><%= l(:text_select_project_modules) %></legend>

<% Redmine::AccessControl.available_project_modules.each do |m| %>
<p><label><%= check_box_tag 'enabled_module_names[]', m, @project.module_enabled?(m) -%>
 <%= l_or_humanize(m, :prefix => "project_module_") %></label></p>
<% end %>
</fieldset>
</div>

<p><%= check_all_links 'modules-form' %></p>
<p><%= submit_tag l(:button_save) %></p>

<% end %>

overlay/var/www/railsapp/app/views/projects/settings/_repositories.html.erb
<% if @project.repositories.any? %>
<table class="list">
  <thead>
    <tr>
      <th><%= l(:label_scm) %></th>
      <th><%= l(:field_identifier) %></th>
      <th><%= l(:field_repository_is_default) %></th>
      <th><%= l(:label_repository) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @project.repositories.sort.each do |repository| %>
    <tr class="<%= cycle 'odd', 'even' %>">
      <td><%=h repository.scm_name %></td>
      <td><%=h repository.identifier %></td>
      <td align="center"><%= checked_image repository.is_default? %></td>
      <td><%=h repository.url %></td>
      <td class="buttons">
      <% if User.current.allowed_to?(:manage_repository, @project) %>
        <%= link_to(l(:label_user_plural), committers_repository_path(repository),
             :class => 'icon icon-user') %>
        <%= link_to(l(:button_edit), edit_repository_path(repository),
             :class => 'icon icon-edit') %>
        <%= link_to(l(:button_delete), repository_path(repository),
            :confirm => l(:text_are_you_sure),
            :method  => :delete,
            :class   => 'icon icon-del') %>
      <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% if User.current.allowed_to?(:manage_repository, @project) %>
  <p><%= link_to l(:label_repository_new), new_project_repository_path(@project), :class => 'icon icon-add' %></p>
<% end %>

overlay/var/www/railsapp/app/views/projects/settings/_wiki.html.erb
<% labelled_remote_form_for :wiki, @wiki,
                   :url => { :controller => 'wikis', :action => 'edit', :id => @project } do |f| %>

<%= error_messages_for 'wiki' %>

<div class="box tabular">
<p><%= f.text_field :start_page, :size => 60, :required => true %>
<em class="info"><%= l(:text_unallowed_characters) %>: , . / ? ; : |</em></p>
</div>

<div class="contextual">
<%= link_to(l(:button_delete), {:controller => 'wikis', :action => 'destroy', :id => @project},
            :class => 'icon icon-del') if @wiki && !@wiki.new_record? %>
</div>

<%= submit_tag((@wiki.nil? || @wiki.new_record?) ? l(:button_create) : l(:button_save)) %>
<% end %>